# Generated by Django 4.0.4 on 2022-05-04 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiro_nome', models.CharField(help_text='Primeiro nome do autor', max_length=100)),
                ('sobrenome', models.CharField(help_text='sobrenome do autor', max_length=100)),
                ('edicao', models.CharField(help_text='edicao do livro', max_length=10, null=True)),
                ('data_nascimento', models.DateField(blank=True, default=None, help_text='Data de nascimento do autor', null=True, verbose_name='Data de nascimento')),
                ('data_morte', models.DateField(blank=True, default=None, help_text='Data de morte do autor', null=True, verbose_name='Data do óbito')),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Genero de um livro', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Idioma de um livro', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Titulo do livro', max_length=200)),
                ('sumario', models.TextField(help_text='Sumario do livro', max_length=2000)),
                ('edicao', models.CharField(help_text='Titulo do livro', max_length=20)),
                ('isbn', models.CharField(help_text='ISBN do livro', max_length=13, unique=True, verbose_name='ISBN')),
                ('autor', models.ForeignKey(help_text='Autor do livro', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalago.autor')),
                ('generos', models.ManyToManyField(to='catalago.genero')),
                ('idioma', models.ForeignKey(help_text='Idioma do livro', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalago.idioma')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_review', models.DateTimeField(auto_now_add=True)),
                ('resumo', models.CharField(help_text='Headline da review', max_length=200)),
                ('review', models.TextField(help_text='Conteúdo da review', max_length=2000)),
                ('status', models.CharField(choices=[('e', 'Em análise'), ('r', 'Reprovada'), ('a', 'Aprovada')], default='a', help_text='Status do review', max_length=1)),
                ('livro', models.ForeignKey(help_text='Autor do livro', on_delete=django.db.models.deletion.CASCADE, to='catalago.livro')),
            ],
        ),
    ]
