# Generated by Django 4.0.4 on 2022-05-19 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalago', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='avaliador',
            field=models.ForeignKey(help_text='Usuário que avaliou esta review', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_avaliador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='revisor',
            field=models.ForeignKey(help_text='Usuário que criou a review', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_revisor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('e', 'Em análise'), ('r', 'Reprovada'), ('a', 'Aprovada')], default='e', help_text='Status do review', max_length=1),
        ),
    ]
