# Generated by Django 4.0.4 on 2022-05-19 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalago', '0002_review_avaliador_review_revisor_alter_review_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'permissions': (('pode_avaliar_review', 'Pode avaliar uma review cadastrada'),)},
        ),
    ]
